services:
  nginx:
    image: nginx:alpine
    hostname: rinha-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "48MB"

  backend-api-1: &api
    image: ricassiocosta/rinha-backend-2025-python:v0.9.0
    hostname: rinha-backend-api-1
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
      - MAX_PARALLELISM=8
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "108MB"

  backend-api-2:
    <<: *api
    hostname: rinha-backend-api-2

  health-check:
    image: ricassiocosta/rinha-backend-2025-python:v0.9.0
    hostname: rinha-health-check
    command: ["python", "-m", "app.health_check"]
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "43MB"

  redis:
    image: redis:7-alpine
    hostname: rinha-redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "5000",
      ]
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "43MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
