services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "12MB"

  backend-api-1:
    build: .
    container_name: rinha-backend-api-1
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://rinha:rinha@postgres:5432/rinha
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  backend-api-2:
    build: .
    container_name: rinha-backend-api-2
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://rinha:rinha@postgres:5432/rinha
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  worker:
    build: .
    container_name: rinha-worker
    command: ["python", "-m", "app.worker"]
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+asyncpg://rinha:rinha@postgres:5432/rinha
      - CONSUMER_NAME=worker
      - MAX_PARALLELISM=64
    depends_on:
      - redis
      - postgres
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: "120MB"

  health-worker:
    build: .
    container_name: rinha-health-worker
    command: ["python", "-m", "app.health_worker"]
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "12MB"

  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "15000",
      ]
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"

  postgres:
    image: postgres:16-alpine
    container_name: rinha-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c fsync=off
      -c autovacuum=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c max_wal_senders=0
      -c wal_level=minimal
      -c shared_buffers=32MB
      -c work_mem=1MB
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "116MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
