services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-api-1
      - backend-api-2
      - backend-api-3
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "48MB"

  backend-api-1: &api
    image: ricassiocosta/rinha-backend-2025-python:v0.10.0
    container_name: rinha-api-1
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379/0
      - MAX_PARALLELISM=5
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "72MB"

  backend-api-2:
    <<: *api
    container_name: rinha-api-2

  backend-api-3:
    <<: *api
    container_name: rinha-api-3

  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "5000",
      ]
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "86MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
